### ISSUE TITLE
[Question] road label

### ISSUE THREAD

**Issue by hanc2006** [GlobeletJS/vector-map#2]
I am trying to use a custom style but I cannot see the road label. Are they currently supported?

![road label](https://i.imgur.com/ei7ZLWR.png)

**Comment by jjhembd** [comment]
Hi, sorry for the late response. "symbol" layers are currently only working for features with "Point" geometry, so road labels are not working yet.

**Comment by jjhembd** [comment]
Hi @hanc2006 , road labels have been implemented in [v0.1.3](https://github.com/GlobeletJS/tile-setter/releases/tag/v0.1.3). 
It is a rough implementation for now, simply fitting a line to the road geometry at the label location. If the curvature of the road is too much for a linear fit, the label at that location is discarded.

![image](https://user-images.githubusercontent.com/41167620/139150061-ded85994-5175-43cc-b511-62af5b5b2ae4.png)

I'd be glad to hear if this works for your style or not.
Thanks again for your feedback!
